<!DOCTYPE library [
<!ELEMENT library (books,members)>
<!ELEMENT books (book1,book2)>
<!ELEMENT book1 (title,author,price)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT book2 (title,author,price)>
<!ELEMENT title (#PCDATA)>
<!ELEMENT author (#PCDATA)>
<!ELEMENT price (#PCDATA)>
<!ELEMENT members (member1,member2)>
<!ELEMENT member1 (name,age,phno)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT phno (#PCDATA)>
<!ELEMENT member2 (name,age,phno)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT age (#PCDATA)>
<!ELEMENT phno (#PCDATA)>
<!ATTLIST book1 bookId CDATA #REQUIRED>
<!ATTLIST book2 bookId CDATA #REQUIRED>
<!ATTLIST member1 memberId CDATA #REQUIRED>
<!ATTLIST member2 memberId CDATA #REQUIRED>
]>
<library>
<books>
      <book1 bookId="1">
            <title>Tales</title>
            <author>Reva</author>
            <price>Rs.500</price>
       </book1>
       <book2 bookId="2">
             <title>Miraculous</title>
             <author>shannon</author>
             <price>Rs.1000</price>
        </book2>
</books>
<members>
      <member1 memberId="1">
             <name>Chloee</name>
             <age>16</age>
             <phno>456790</phno>
         </member1>
      <member2 memberId="2">
              <name>Aliya</name>
              <age>16</age>
               <phno>235632</phno>
          </member2>
</members>
</library>

